from math import atan

# Font
AUTHOR = "CraftedFury"
FONT_NAME = "Minecraft"
VERSION = "1.1.0"
MAC_EPOCH = 2082844800 # FontTools requires seconds since 12:00 midnight, January 1, 1904 UTC

# Glyph
BOUNDING_BOX = [0, -128, 1152, 896]
UNITS_PER_EM = 1024
ASCENT = BOUNDING_BOX[3]
DESCENT = BOUNDING_BOX[1]
ADVANCE_WIDTH = BOUNDING_BOX[2] + BOUNDING_BOX[1]
NOTDEF = ".notdef"
NOTDEF_GLYPH = [20, 0, 437, 675]

# Italic Glyph
ITALIC_SHEAR_VERTICAL = 5
ITALIC_SHEAR_FACTOR = 1 / ITALIC_SHEAR_VERTICAL
ITALIC_SHEAR_ANGLE = atan(ITALIC_SHEAR_FACTOR)

# Bitmap Glyph
BITMAP_GLYPH_SIZE = 8
BITMAP_COLUMNS = 16
